"""Dependency-free contracts shared across OpenWAM subsystems."""

from .latent_space import (
    VIDEO_LATENT_SPACE_SCHEMA_V1,
    VideoLatentSpaceIdentity,
    identify_video_latent_space,
    require_compatible_video_latent_spaces,
)
from .paths import REPO_ROOT, find_repo_root, resolve_repo_path
from .sample_metadata import (
    DYNAMICS_CONDITIONAL_CHUNK_LAYOUT_METADATA_KEY,
    DYNAMICS_CONDITIONAL_CHUNK_LAYOUT_T0_SINGLETON,
    DYNAMICS_CONDITIONAL_HISTORY_POLICY_METADATA_KEY,
    DYNAMICS_CONDITIONAL_HISTORY_PREVIOUS_BOUNDARY_VIDEO_ONLY,
    DYNAMICS_CONDITIONAL_LAYOUT_METADATA_KEY,
    DYNAMICS_CONDITIONAL_LAYOUT_TARGET_ONLY_T0_PLUS_FUTURE,
    DYNAMICS_ROUTING_BUCKET_METADATA_KEY,
    DYNAMICS_ROUTING_DROP_TEXT_METADATA_KEY,
    DYNAMICS_ROUTING_MODE_METADATA_KEY,
    DYNAMICS_ROUTING_SOURCE_METADATA_KEY,
    ConditionalDynamicsSequenceLayout,
    DynamicsRoutingSampleMetadata,
    SampleConstructionMetadata,
    single_sample_metadata_mapping,
)
from .video import (
    WAN_TEMPORAL_CHUNK_SIZE,
    CanonicalViewLayout,
    FpsSource,
    ResolvedSourceFps,
    ResolvedVideoClip,
    VideoFrameMapping,
    ViewPlacement,
    normalized_video_frame_count,
    resolve_video_source_fps,
    wan_fully_observed_latent_count,
    wan_raw_frame_count_to_latent_count,
    wan_safe_temporal_frame_count,
)

__all__ = [
    "DYNAMICS_CONDITIONAL_CHUNK_LAYOUT_METADATA_KEY",
    "DYNAMICS_CONDITIONAL_CHUNK_LAYOUT_T0_SINGLETON",
    "DYNAMICS_CONDITIONAL_HISTORY_POLICY_METADATA_KEY",
    "DYNAMICS_CONDITIONAL_HISTORY_PREVIOUS_BOUNDARY_VIDEO_ONLY",
    "DYNAMICS_CONDITIONAL_LAYOUT_METADATA_KEY",
    "DYNAMICS_CONDITIONAL_LAYOUT_TARGET_ONLY_T0_PLUS_FUTURE",
    "DYNAMICS_ROUTING_BUCKET_METADATA_KEY",
    "DYNAMICS_ROUTING_DROP_TEXT_METADATA_KEY",
    "DYNAMICS_ROUTING_MODE_METADATA_KEY",
    "DYNAMICS_ROUTING_SOURCE_METADATA_KEY",
    "REPO_ROOT",
    "VIDEO_LATENT_SPACE_SCHEMA_V1",
    "WAN_TEMPORAL_CHUNK_SIZE",
    "CanonicalViewLayout",
    "ConditionalDynamicsSequenceLayout",
    "DynamicsRoutingSampleMetadata",
    "FpsSource",
    "ResolvedSourceFps",
    "ResolvedVideoClip",
    "SampleConstructionMetadata",
    "VideoFrameMapping",
    "VideoLatentSpaceIdentity",
    "ViewPlacement",
    "find_repo_root",
    "identify_video_latent_space",
    "normalized_video_frame_count",
    "require_compatible_video_latent_spaces",
    "resolve_repo_path",
    "resolve_video_source_fps",
    "single_sample_metadata_mapping",
    "wan_fully_observed_latent_count",
    "wan_raw_frame_count_to_latent_count",
    "wan_safe_temporal_frame_count",
]
