"""Shared model utilities reused across policy variants and decoders."""

from .attention_backends import (
    apply_attention_backend,
    resolve_attention_profile_backend,
    select_attention_profile_mask,
)
from .attention_contracts import (
    AttentionProfileSpec,
    PreparedAttentionProfile,
    chunked_temporal_exact_coupling_from_profile_name,
    chunked_temporal_exact_profile_name_for_coupling,
    normalize_attention_profile_name,
    normalize_chunked_temporal_exact_coupling,
)
from .chunked_attention import (
    build_chunked_conditioned_video_attention_profile,
    build_chunked_temporal_exact_attention_profile,
    build_lingbot_chunked_exact_attention_profile,
)
from .cache_layout_policy import (
    merge_attention_cache_entries,
    packed_slot_pool_query_sequence_ids,
    prepend_cached_prefix_mask,
    prepare_sdpa_mask,
    resolve_slot_pool_prefix_visibility,
    retained_slot_pool_indices_for_current_write,
)
from .cache_backend_contracts import (
    CacheBackendSpec,
    MergedPrefixCachePayload,
    SLOT_POOL_ALLOW_VIDEO_TO_ACTION_PREFIX_TAIL_TOKENS,
    SLOT_POOL_DEFER_EVICTION_UNTIL_AFTER_WRITE_ATTENTION,
    SlotPoolCachePayload,
    SlotPoolLayerState,
    cache_backend_uses_slot_pool,
    resolve_cache_backend_spec,
)
from .cache_backend_lifecycle import (
    allocate_slot_pool_slots,
    clear_cache_backend_payload,
    init_cache_backend_payload,
    materialize_cache_backend_entries,
    materialize_slot_pool_layer_entry,
    next_slot_pool_cache_id,
    restore_slot_pool_slots,
    update_slot_pool_layer_state,
)
from .flow_training import (
    ActionFlowMatchTrainArtifacts,
    BlockCoupledActionFlowMatchTrainArtifacts,
    FrameAlignedActionFlowMatchTrainArtifacts,
    build_action_flow_match_train_artifacts,
    build_block_coupled_action_flow_match_train_artifacts,
    build_frame_aligned_action_flow_match_train_artifacts,
    build_video_flow_match_train_artifacts,
)
from .flow_schedule import (
    FlowMatchScheduler,
    expand_scalar_timestep,
    explicit_sigma_euler_step,
    sample_timestep_id,
    zero_terminal_next_sigma,
)
from .flow_inference import (
    build_action_flow_match_inference_scheduler,
    build_flow_unipc_inference_scheduler,
    build_video_flow_match_inference_scheduler,
)
from .flow_supervision import (
    build_video_frame_loss_mask,
    denoised_actions_from_flow,
    denoised_video_latents_from_flow,
    reduce_frame_aligned_action_flow_match_loss,
    reduce_slot_aligned_action_flow_match_loss,
    reduce_video_flow_match_loss,
)
from .flow_unipc_multistep_scheduler import FlowUniPCMultistepScheduler
from .packed_token_layout import (
    PackedTokenKind,
    PackedTokenLayout,
    PackedTokenStream,
    build_exact_conditioned_video_token_layout,
    build_exact_video_action_token_layout,
    flatten_action_token_mask,
)
from .runtime_controls import (
    JointRuntimeSchedulers,
    RuntimeCachePolicy,
    RuntimeGuidanceConfig,
    RuntimeWarmupReference,
    build_joint_video_timestep_grid,
    build_joint_runtime_schedulers,
    build_unconditional_conditioning,
    combine_cfg_prediction,
    combine_joint_cfg_predictions,
    preserve_joint_observed_video_prefix,
    resolve_runtime_cache_branch,
    resolve_runtime_cache_branches,
    resolve_runtime_warmup_reference,
    resolve_runtime_guidance,
    resolve_runtime_cache_policy,
    should_update_cache_during_denoise,
)
from .rollout import RolloutCursor, advance_rollout_cursor
from .temporal_windows import (
    OneFrameConditionedHistoryWindow,
    resolve_interleaved_cache_frames,
    resolve_interleaved_history_frames,
    resolve_one_frame_conditioned_history_window,
)
from .sharded_execution import (
    checkpoint_unshard_context,
    summon_full_parameters,
    unshard_runtime_parameters,
)
from .video_geometry import (
    slice_token_grid_frames,
    unpatchify_video_sequence,
    unpatchify_video_tokens,
    video_token_grid_from_latent_shape,
)

__all__ = [
    "AttentionProfileSpec",
    "ActionFlowMatchTrainArtifacts",
    "BlockCoupledActionFlowMatchTrainArtifacts",
    "CacheBackendSpec",
    "FrameAlignedActionFlowMatchTrainArtifacts",
    "FlowMatchScheduler",
    "FlowUniPCMultistepScheduler",
    "PreparedAttentionProfile",
    "PackedTokenKind",
    "PackedTokenLayout",
    "PackedTokenStream",
    "OneFrameConditionedHistoryWindow",
    "JointRuntimeSchedulers",
    "MergedPrefixCachePayload",
    "RuntimeCachePolicy",
    "RuntimeWarmupReference",
    "RolloutCursor",
    "RuntimeGuidanceConfig",
    "SLOT_POOL_ALLOW_VIDEO_TO_ACTION_PREFIX_TAIL_TOKENS",
    "SLOT_POOL_DEFER_EVICTION_UNTIL_AFTER_WRITE_ATTENTION",
    "SlotPoolCachePayload",
    "SlotPoolLayerState",
    "allocate_slot_pool_slots",
    "cache_backend_uses_slot_pool",
    "checkpoint_unshard_context",
    "build_joint_video_timestep_grid",
    "apply_attention_backend",
    "build_chunked_temporal_exact_attention_profile",
    "build_chunked_conditioned_video_attention_profile",
    "chunked_temporal_exact_coupling_from_profile_name",
    "chunked_temporal_exact_profile_name_for_coupling",
    "build_action_flow_match_inference_scheduler",
    "build_action_flow_match_train_artifacts",
    "build_block_coupled_action_flow_match_train_artifacts",
    "build_joint_runtime_schedulers",
    "build_lingbot_chunked_exact_attention_profile",
    "build_exact_video_action_token_layout",
    "build_exact_conditioned_video_token_layout",
    "build_frame_aligned_action_flow_match_train_artifacts",
    "build_flow_unipc_inference_scheduler",
    "build_unconditional_conditioning",
    "combine_cfg_prediction",
    "combine_joint_cfg_predictions",
    "resolve_runtime_cache_branch",
    "resolve_runtime_cache_branches",
    "clear_cache_backend_payload",
    "materialize_cache_backend_entries",
    "materialize_slot_pool_layer_entry",
    "merge_attention_cache_entries",
    "next_slot_pool_cache_id",
    "packed_slot_pool_query_sequence_ids",
    "prepend_cached_prefix_mask",
    "prepare_sdpa_mask",
    "preserve_joint_observed_video_prefix",
    "build_video_flow_match_inference_scheduler",
    "build_video_frame_loss_mask",
    "build_video_flow_match_train_artifacts",
    "denoised_actions_from_flow",
    "denoised_video_latents_from_flow",
    "expand_scalar_timestep",
    "explicit_sigma_euler_step",
    "advance_rollout_cursor",
    "reduce_frame_aligned_action_flow_match_loss",
    "reduce_slot_aligned_action_flow_match_loss",
    "reduce_video_flow_match_loss",
    "resolve_runtime_cache_policy",
    "resolve_attention_profile_backend",
    "normalize_attention_profile_name",
    "normalize_chunked_temporal_exact_coupling",
    "resolve_cache_backend_spec",
    "resolve_slot_pool_prefix_visibility",
    "resolve_runtime_warmup_reference",
    "resolve_runtime_guidance",
    "resolve_interleaved_cache_frames",
    "resolve_interleaved_history_frames",
    "resolve_one_frame_conditioned_history_window",
    "sample_timestep_id",
    "select_attention_profile_mask",
    "flatten_action_token_mask",
    "slice_token_grid_frames",
    "restore_slot_pool_slots",
    "retained_slot_pool_indices_for_current_write",
    "should_update_cache_during_denoise",
    "summon_full_parameters",
    "init_cache_backend_payload",
    "update_slot_pool_layer_state",
    "unpatchify_video_tokens",
    "unpatchify_video_sequence",
    "unshard_runtime_parameters",
    "video_token_grid_from_latent_shape",
    "zero_terminal_next_sigma",
]
