from __future__ import annotations

import argparse
import json
import re
import shutil
from collections.abc import Iterable
from pathlib import Path
from urllib.parse import unquote, urlsplit

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / ".docs_site"
PUBLIC_DOCS = REPO_ROOT / "docs"
OUTPUT_SENTINEL = ".open_wam_generated_docs"
TEXT_SUFFIXES = {".csv", ".json", ".md", ".txt", ".yaml", ".yml"}
PUBLIC_MARKDOWN_PATHS = (
    Path("architecture.md"),
    Path("artifacts.md"),
    Path("benchmarks.md"),
    Path("cards/README.md"),
    Path("cards/public_tiny_synthetic_contract.md"),
    Path("cli.md"),
    Path("compatibility.md"),
    Path("cookbooks/new_action_decoder.md"),
    Path("cookbooks/new_dataset.md"),
    Path("cookbooks/new_policy_architecture.md"),
    Path("cookbooks/new_simulator_adapter.md"),
    Path("cookbooks/reproduce_result.md"),
    Path("experiment_cards.md"),
    Path("extension_sdk.md"),
    Path("index.md"),
    Path("lingbot_va_baseline_libero10.md"),
    Path("migration_0_2.md"),
    Path("policy_architectures.md"),
    Path("pretraining/index.md"),
    Path("pretraining/batching.md"),
    Path("pretraining/data_processing.md"),
    Path("pretraining/datasets.md"),
    Path("pretraining/multiview_training.md"),
    Path("pretraining/storage.md"),
    Path("pretraining/training.md"),
    Path("pretraining/validation.md"),
    Path("quickstart.md"),
    Path("release.md"),
    Path("reproducibility.md"),
    Path("rollout_contracts.md"),
    Path("running_experiments.md"),
    Path("testing.md"),
    Path("variable_length_training_batches.md"),
    Path("video_action_composition.md"),
    Path("video_only_training.md"),
)
PUBLIC_ASSET_PATHS = (
    Path("assets/robot-teaser.gif"),
    Path("assets/pretraining/datasets.yaml"),
    Path("assets/affiliations/SOURCES.txt"),
    Path("assets/affiliations/stanford-ai-lab.jpg"),
    Path("assets/affiliations/stanford-src.webp"),
    Path("assets/affiliations/stanford-stai.png"),
    Path("assets/affiliations/stanford-svl.png"),
    Path("assets/affiliations/stanford-wordmark.png"),
    Path("assets/stylesheets/openwam.css"),
)
_MARKDOWN_LINK = re.compile(r"!?\[[^\]]*\]\(\s*(?P<target><[^>]+>|[^)\s]+)")
_REPOSITORY_REFERENCE = re.compile(
    r"(?<![\w./-])(?P<target>(?:src/open_wam|scripts|configs|examples)/"
    r"[A-Za-z0-9_./<>-]+\.(?:py|sh|yaml|yml|md))"
)
GENERATED_REPOSITORY_PATHS = frozenset(
    {
        "configs/artifacts.yaml",
        "configs/local_paths.yaml",
    }
)

FORBIDDEN_PUBLIC_FRAGMENTS = (
    "/simurgh",
    "/afs/",
    "/hai/",
    "/sailhome",
    "/scr/",
    "/home/",
    "WANDB_API_KEY",
    "api_key:",
    "secret:",
)


def main() -> None:
    parser = argparse.ArgumentParser(description="Stage curated public docs for MkDocs.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Generated MkDocs docs_dir.")
    args = parser.parse_args()

    summary = build_docs_site(args.output)
    print(json.dumps(summary, indent=2, sort_keys=True))


def build_docs_site(output: Path) -> dict[str, int | str | bool]:
    output = _validate_output_dir(output)
    if output.exists():
        _clear_generated_output(output)
    output.mkdir(parents=True, exist_ok=True)
    (output / OUTPUT_SENTINEL).write_text("generated by scripts/build_docs_site.py\n", encoding="utf-8")

    source_pages = tuple(PUBLIC_DOCS / relative for relative in PUBLIC_MARKDOWN_PATHS)
    reference_pages = (*source_pages, REPO_ROOT / "README.md")
    missing_references = scan_missing_repository_paths(reference_pages)
    if missing_references:
        formatted = "\n".join(
            f"{path}:{line}: {target}" for path, line, target in missing_references[:20]
        )
        raise SystemExit(f"Public docs reference missing repository paths:\n{formatted}")

    public_pages = _stage_public_markdown(PUBLIC_DOCS, output)
    public_assets = _stage_public_assets(PUBLIC_DOCS, output)

    leaks = scan_private_fragments(output)
    if leaks:
        formatted = "\n".join(f"{path}:{line}: {fragment}" for path, line, fragment in leaks[:20])
        raise SystemExit(f"Generated docs still contain private fragments:\n{formatted}")

    broken_links = scan_broken_local_links(output)
    if broken_links:
        formatted = "\n".join(f"{path}:{line}: {target}" for path, line, target in broken_links[:20])
        raise SystemExit(f"Generated docs contain broken or escaping local links:\n{formatted}")

    return {
        "docs_dir": str(output),
        "public_assets": public_assets,
        "public_pages": public_pages,
        "notes_published": False,
        "private_leaks": len(leaks),
        "broken_local_links": len(broken_links),
        "missing_repository_paths": len(missing_references),
    }


def _validate_output_dir(output: Path) -> Path:
    raw_output = output.expanduser()
    for path in (raw_output, *raw_output.parents):
        if path.exists() and path.is_symlink():
            raise SystemExit(f"Refusing to use symlinked docs output path: {path}")

    resolved_output = raw_output.resolve()
    home = Path.home().resolve()
    if resolved_output == resolved_output.parent:
        raise SystemExit("Refusing to use the filesystem root as the generated docs output.")
    if resolved_output == home:
        raise SystemExit("Refusing to use the home directory as the generated docs output.")
    if resolved_output == REPO_ROOT:
        raise SystemExit("Refusing to use the repository root as the generated docs output.")
    if resolved_output.exists() and not resolved_output.is_dir():
        raise SystemExit(f"Refusing to use non-directory docs output path: {resolved_output}")
    if resolved_output.exists() and any(resolved_output.iterdir()) and not (resolved_output / OUTPUT_SENTINEL).is_file():
        raise SystemExit(
            f"Refusing to clear non-generated docs output directory: {resolved_output}. "
            f"Expected sentinel file {OUTPUT_SENTINEL!r}."
        )
    return resolved_output


def _clear_generated_output(output: Path) -> None:
    for child in output.iterdir():
        if child.is_dir() and not child.is_symlink():
            shutil.rmtree(child)
        else:
            child.unlink()


def scan_private_fragments(root: Path) -> list[tuple[str, int, str]]:
    leaks: list[tuple[str, int, str]] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in TEXT_SUFFIXES.union({".html"}):
            continue
        for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            for fragment in FORBIDDEN_PUBLIC_FRAGMENTS:
                if fragment in line:
                    leaks.append((str(path.relative_to(root)), line_number, fragment))
    return leaks


def scan_broken_local_links(
    root: Path,
    markdown_paths: Iterable[Path] | None = None,
) -> list[tuple[str, int, str]]:
    root = root.resolve()
    broken: list[tuple[str, int, str]] = []
    paths = root.rglob("*.md") if markdown_paths is None else markdown_paths
    for path in sorted(path.resolve() for path in paths):
        text = path.read_text(encoding="utf-8")
        for match in _MARKDOWN_LINK.finditer(text):
            target = match.group("target").strip("<>")
            parsed = urlsplit(target)
            if parsed.scheme or parsed.netloc or not parsed.path:
                continue
            destination = (path.parent / unquote(parsed.path)).resolve()
            if not destination.is_relative_to(root) or not destination.exists():
                line = text.count("\n", 0, match.start()) + 1
                broken.append((str(path.relative_to(root)), line, target))
    return broken


def scan_missing_repository_paths(
    markdown_paths: Iterable[Path],
    repository_root: Path = REPO_ROOT,
) -> list[tuple[str, int, str]]:
    repository_root = repository_root.resolve()
    missing: list[tuple[str, int, str]] = []
    for path in sorted(path.resolve() for path in markdown_paths):
        text = path.read_text(encoding="utf-8")
        for match in _REPOSITORY_REFERENCE.finditer(text):
            target = match.group("target")
            if "<" in target or target in GENERATED_REPOSITORY_PATHS:
                continue
            if not (repository_root / target).is_file():
                line = text.count("\n", 0, match.start()) + 1
                missing.append((str(path.relative_to(repository_root)), line, target))
    return missing


def _stage_public_markdown(source: Path, target: Path) -> int:
    expected = set(PUBLIC_MARKDOWN_PATHS)
    actual = {path.relative_to(source) for path in source.rglob("*.md") if path.is_file()}
    missing = sorted(expected - actual)
    unclassified = sorted(actual - expected)
    if missing or unclassified:
        details = []
        if missing:
            details.append("missing=" + ", ".join(map(str, missing)))
        if unclassified:
            details.append("unclassified=" + ", ".join(map(str, unclassified)))
        raise SystemExit("Public documentation inventory mismatch: " + "; ".join(details))

    for source_relative in PUBLIC_MARKDOWN_PATHS:
        path = source / source_relative
        relative = _site_relative_path(source_relative)
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
    return len(PUBLIC_MARKDOWN_PATHS)


def _stage_public_assets(source: Path, target: Path) -> int:
    asset_root = source / "assets"
    expected = set(PUBLIC_ASSET_PATHS)
    actual = {
        path.relative_to(source)
        for path in asset_root.rglob("*")
        if path.is_file()
    }
    missing = sorted(expected - actual)
    unclassified = sorted(actual - expected)
    if missing or unclassified:
        details = []
        if missing:
            details.append("missing=" + ", ".join(map(str, missing)))
        if unclassified:
            details.append("unclassified=" + ", ".join(map(str, unclassified)))
        raise SystemExit("Public documentation asset inventory mismatch: " + "; ".join(details))

    for relative in PUBLIC_ASSET_PATHS:
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source / relative, destination)
    return len(PUBLIC_ASSET_PATHS)


def _site_relative_path(relative: Path) -> Path:
    if relative.name == "README.md":
        return relative.with_name("index.md")
    return relative


if __name__ == "__main__":
    main()
